# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-node-browsers
    environment:
      GIT_EMAIL: "$(git log HEAD^..HEAD --pretty='%aE' | sort -u)"
      GIT_NAME: "$(git log HEAD^..HEAD --pretty='%aN' | sort -u)"
    steps:
      - checkout
      - run:
          name: Install NPM & GULP
          command: |
                sudo npm install -g npm@latest
                sudo npm install -g gulp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: RUN NPM INSTALL IN PROJECT
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: RUN GULP BUILD IN PROJECT
          command: gulp build
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          command: echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run:
          name: PUSH NEW CHANGES TO WPEngine
          command: |
                echo Cloning WPE
                git config --global user.email "$GIT_EMAIL"
                git config --global user.name "$GIT_NAME"
                mkdir -p ~/wpe/
                git clone "$WP_ENGINE_GIT_REMOTE" -q
                cd "$WP_PROJECT_FOLDER"
                rm -rf wp-content/plugins/laterpay
                cp -r ~/repo/laterpay/ wp-content/plugins/laterpay
                git add . && git commit -m "Master Build Pushed on `date +'%Y-%m-%d %H:%M:%S'`" -q && git push origin -q